const translations={
  zh:{'nav.about':'關於','nav.work':'精選事蹟','nav.contact':'聯絡','hero.eyebrow':'數位產品設計師 · 台北','hero.first':'莊','hero.last':'博勛','hero.intro':'我把複雜的問題，設計成讓人想靠近的體驗。<br>以好奇心為介面，以人為核心。','hero.cta':'一起創造些什麼','hero.scroll':'向下探索 <span>↓</span>','hero.role':'產品設計 · 品牌體驗 · 創意程式','about.label':'關於我','about.title':'我相信好的設計，<br><i>會留下感覺。</i>','about.body':'嗨，我是博勛，一位住在台北的數位產品設計師。過去 7 年，我在新創、文化科技與永續團隊之間，為真實的人設計更清晰、更有溫度的數位體驗。','about.body2':'下班後，我收集城市的聲音、研究手沖咖啡，也在山徑與底片相機之間，找回慢下來的節奏。','about.link':'認識我的旅程 <span>→</span>','stats.years':'年設計經驗','stats.products':'參與產品專案','stats.countries':'合作國家／地區','stats.coffee':'杯手沖咖啡','work.label':'精選事蹟','work.title':'一些把想像<br><i>變成現實的時刻。</i>','project.one.title':'讓海岸保育，成為每日行動','project.one.desc':'潮汐公民科學平台','project.two.title':'為獨立書店打造一座雲端島嶼','project.two.desc':'晝夜書店數位體驗','project.three.title':'讓資料不只被看見，也被感受','project.three.desc':'城市氣候互動展演','play.eyebrow':'近期探索中','play.title':'我最近著迷於<br><i>聲音與空間。</i>','play.body':'用程式把台北的雨聲，編織成一場可觸摸的視覺演出。','contact.label':'聯絡我','contact.eyebrow':'有個發亮的點子嗎？','contact.title':'讓我們一起<br><i>把它變得精彩。</i>','footer':'以好奇心製作於台北 · 2026'},
  en:{'nav.about':'ABOUT','nav.work':'SELECTED WORK','nav.contact':'CONTACT','hero.eyebrow':'DIGITAL PRODUCT DESIGNER · TAIPEI','hero.first':'PO-HSUN','hero.last':'CHUANG','hero.intro':'I turn complex questions into experiences<br>people want to lean into — with curiosity, for humans.','hero.cta':'MAKE SOMETHING TOGETHER','hero.scroll':'SCROLL TO EXPLORE <span>↓</span>','hero.role':'PRODUCT DESIGN · BRAND EXPERIENCE · CREATIVE CODE','about.label':'ABOUT ME','about.title':'I BELIEVE GREAT DESIGN<br><i>LEAVES A FEELING.</i>','about.body':'Hi, I’m Po-Hsun, a digital product designer based in Taipei. For seven years, I’ve worked across startups, culture-tech and sustainability teams to make digital experiences clearer and warmer for real people.','about.body2':'Off the clock, I collect city sounds, obsess over pour-over coffee, and find a slower rhythm between mountain trails and film cameras.','about.link':'FOLLOW MY JOURNEY <span>→</span>','stats.years':'YEARS OF DESIGN','stats.products':'PRODUCTS SHIPPED','stats.countries':'MARKETS COLLABORATED','stats.coffee':'POUR-OVER CUPS','work.label':'SELECTED WORK','work.title':'MOMENTS OF TURNING<br><i>IMAGINATION INTO REALITY.</i>','project.one.title':'Making coastal conservation a daily action','project.one.desc':'Tidal citizen-science platform','project.two.title':'A cloud island for an independent bookstore','project.two.desc':'Day & Night Books digital experience','project.three.title':'Data that is felt, not just seen','project.three.desc':'City climate interactive installation','play.eyebrow':'CURRENTLY EXPLORING','play.title':'RECENTLY OBSESSED WITH<br><i>SOUND & SPACE.</i>','play.body':'Weaving the sound of Taipei rain into a tangible visual performance through code.','contact.label':'CONTACT','contact.eyebrow':'HAVE A BRIGHT IDEA?','contact.title':'LET’S MAKE IT<br><i>WORTH FEELING.</i>','footer':'MADE WITH CURIOSITY IN TAIPEI · 2026'}
};
let lang='zh';const root=document.documentElement;const languageToggle=document.querySelector('#languageToggle');
function setLanguage(next){lang=next;document.querySelectorAll('[data-i18n]').forEach(el=>el.innerHTML=translations[lang][el.dataset.i18n]);languageToggle.textContent=lang==='zh'?'EN':'中';root.lang=lang==='zh'?'zh-Hant':'en';document.title=lang==='zh'?'莊博勛 — 數位產品設計師':'Po-Hsun Chuang — Digital Product Designer';}
languageToggle.addEventListener('click',()=>setLanguage(lang==='zh'?'en':'zh'));
document.querySelector('#themeToggle').addEventListener('click',()=>{const light=root.dataset.theme==='light';root.dataset.theme=light?'dark':'light';document.querySelector('.theme-icon').textContent=light?'☼':'☾';});
document.addEventListener('mousemove',e=>{const glow=document.querySelector('.cursor-glow');glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px';});
document.querySelectorAll('.tilt-card').forEach(card=>{card.addEventListener('mousemove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(900px) rotateY(${x*7}deg) rotateX(${y*-7}deg)`});card.addEventListener('mouseleave',()=>card.style.transform='');});
if(window.gsap){gsap.registerPlugin(ScrollTrigger);gsap.to('.reveal',{opacity:1,y:0,stagger:.11,duration:1.1,ease:'power4.out',delay:.2});gsap.utils.toArray('.section-title,.contact-title').forEach(el=>gsap.from(el,{scrollTrigger:{trigger:el,start:'top 82%'},y:55,opacity:0,duration:1,ease:'power3.out'}));gsap.utils.toArray('.project-card').forEach((el,i)=>gsap.from(el,{scrollTrigger:{trigger:el,start:'top 88%'},x:i%2?45:-45,opacity:0,duration:.85,ease:'power3.out'}));gsap.from('.stat-card',{scrollTrigger:{trigger:'.stats-grid',start:'top 85%'},y:35,opacity:0,stagger:.12,duration:.7});document.querySelectorAll('[data-count]').forEach(el=>{ScrollTrigger.create({trigger:el,start:'top 88%',once:true,onEnter:()=>gsap.to(el,{innerText:+el.dataset.count,duration:1.3,snap:{innerText:1},ease:'power2.out'})})});gsap.to('.portrait-wrap',{scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1},y:100,rotation:5});}
